module Game
  class Constants

    RELEASE_VERSION = "1.01"
    DEBUG_VERSION = "1.02"
    DEFAULT_INITIAL_TURNS = 40
    TOKEN_GROUP_VALUE = 5
    SUPER_TOKEN_VALUE = 10
    MAX_STACK = 15
    BLOODY_MARY_TURN_GAIN = 5
    BLOODY_MARY_VOMIT_GAIN = 3
    CELLS_CONTAMINATED_ON_VOMIT = 5

  end
end