module Game
  class Constants

    VERSION = 0.99
    INITIAL_TOTAL_TURNS = 40
    TOKEN_GROUP_VALUE = 5
    SUPER_TOKEN_VALUE = 10
    MAX_STACK = 15
    BLOODY_MARY_TURN_GAIN = 5
    BLOODY_MARY_VOMIT_GAIN = 3
    CELLS_CONTAMINATED_ON_VOMIT = 5

  end
end