source 'http://rubygems.org'

RAILS_VERSION = '3.0.0.rc2'
DM_VERSION = '1.0.0'

#gem 'rails',                RAILS_VERSION
#gem 'activerecord',         RAILS_VERSION
#gem 'activeresource',       RAILS_VERSION
gem 'activesupport',        RAILS_VERSION
gem 'actionpack',           RAILS_VERSION
gem 'actionmailer',         RAILS_VERSION
gem 'railties',             RAILS_VERSION

gem 'dm-rails',             '~> 1.0.3'
gem 'dm-sqlite-adapter',     DM_VERSION
#gem 'dm-mysql-adapter',     DM_VERSION
gem 'dm-migrations',        DM_VERSION
gem 'dm-types',             DM_VERSION
gem 'dm-validations',       DM_VERSION
gem 'dm-constraints',       DM_VERSION
gem 'dm-transactions',      DM_VERSION
gem 'dm-aggregates',        DM_VERSION
gem 'dm-timestamps',        DM_VERSION
gem 'dm-observer',          DM_VERSION
gem 'dm-serializer',        DM_VERSION
gem 'dm-adjust',            DM_VERSION

gem 'haml'

gem 'json'
gem 'mini_fb'
