defaults: &defaults
  adapter: mysql
  encoding: UTF-8
  reconnect: false
  pool: 5

development:
  database: beerquest_development
  username: root
  password:
  host: localhost
  <<: *defaults

test:
  database: beerquest_test
  username: beerquest
  password: glouglou
  host: localhost
  <<: *defaults

production:
  adapter: mysql
  database: beerquest
  username: beerquest
  password: glouglou
  host: localhost
  <<: *defaults
