defaults: &defaults
  encoding: UTF-8
  reconnect: false
  pool: 5

development:
  adapter: mysql
  database: beerquest
  username: root
  password: XDu3=Td4
  host: localhost
  port: 3308
  <<: *defaults

test:
  adapter: sqlite
  database: db/beerquest_test.sqlite
  username: root
  password:
  host: localhost
  <<: *defaults

production:
  adapter: mysql
  database: beerquest
  username: beerquest
  password: glouglou
  host: localhost
  <<: *defaults
