defaults: &defaults
  encoding: utf8
  reconnect: false
  pool: 5

development:
  adapter: sqlite
  database: db/beerquest_development.sqlite
  username: root
  password:
  host: localhost
  <<: *defaults

test:
  adapter: sqlite
  database: db/beerquest_test.sqlite
  username: root
  password:
  host: localhost
  <<: *defaults

production:
  adapter: mysql
  database: beerquest_production
  username: beerquest
  password: glouglou
  host: localhost
  <<: *defaults
