defaults: &defaults
  adapter: sqlite
#  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5

development:
  database: beerquest_development.db
#  database: beerquest_development
  username: root
  password:
  host: localhost
  <<: *defaults

test:
  database: beerquest_test
  username: root
  password:
  host: localhost
  <<: *defaults

production:
  database: beerquest_production
  username: beerquest
  password: glouglou
  host: localhost
  <<: *defaults
